// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Packet is an autogenerated mock type for the Packet type
type Packet struct {
	mock.Mock
}

// GetRequestID provides a mock function with given fields:
func (_m *Packet) GetRequestID() []byte {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// IAm provides a mock function with given fields:
func (_m *Packet) IAm() byte {
	ret := _m.Called()

	var r0 byte
	if rf, ok := ret.Get(0).(func() byte); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(byte)
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *Packet) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetRequestID provides a mock function with given fields: id
func (_m *Packet) SetRequestID(id []byte) {
	_m.Called(id)
}
